export default class DayModel {
  constructor() {
    this.days = [
      { titulo: "Día 1", texto: "Hoy es el día 1 del Fantastico mes santo, este mes estara lleno de festejo ya que este mes es el mes en el que nacio la Diosa unica en mi vida y a la que mas AMO, Te amo mi linda Isis." },
      { titulo: "Día 2", texto: "Hoy es el día 2 del hermoso mes santo, en el dia 2 solo quiero pasarlo junto a ti y expresarte mi mas grande cariño mi linda Isis, te AMOOO." },
      { titulo: "Día 3", texto: "Hoy es el día 3 del maginfico mes santo, este dia es tu dia de descanso, que dices quieres pasarlo conmigo? te amo tanto mi linda Isis." },
      { titulo: "Día 4", texto: "Hoy es el día 4 del unico mes santo (aunque cada mes es especial mi hermosa Diosa) este es aun mas por que naciste tuuuuuu, te amo con todo mi corazon." },
      { titulo: "Día 5", texto: "Hoy es el día 5 del espectacular mes santo y quiero decirte que me encanta tu hermosa sonrisa y tus lindos ojos que cuando sonries iluminas mis dias, mi hermosa Diosa, te amo demaciadoooooo." },
      { titulo: "Día 6", texto: "Hoy es el día 6 del glorioso mes santo, que? la razon por la que digo que eres mi diosa? no te lo dije nunca?, pues lo digo mañana sin falta, te amo tanto mi linda Isis eres unica te amo." },
      { titulo: "Día 7", texto: "Hoy es el día 7 del especial mes SANTOOOOOOOO y tambien cumplimos 5 meses juntos, asi que eso lo hace doblemente especial, hoy martes, quiero estar junto a ti, a y si estate atenta a mis mensajes si? si no te lo perderas eh, a sisi la razon por la que te digo mi Diosa, pues te lo digo mañanaaaaa, hoy toca disfrutar si? te amo demaciado mi hermosa y unica Diosa ." },
      { titulo: "Día 8", texto: "Hoy es el día 8 del frutifantastico mes santooo, es vez si te dire por que te digo diosa, pues la razon por la que te lo digo es... pues te lo dire pronto estate atenta te amooooooooo, mi hermosa Diosa Isis" },
      { titulo: "Día 9", texto: "Hoy es el día 9 DEL PRECIOSO MES SANTOOOOOOOOOOOOOO este es el dia que nacio mi hermosa, linda espectacular, unica, angelical Diosa Diosa mia un dia como hoy naciste y seguro que fue el dia que el mundo se detuvo por que naciste tu, eres la persona mas importante de este mundo, y la unica que puedo ver, la unica que me alegra los dias, la unica que me hace querer expresarme te amo tanto mi linda Isis, gracias por existir gracias por estar a mi lado gracias por soportarme y gracias por permitirme estar a tu lado, te amo te amo tanto que no sabes cuanto TE AMOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO." },
      { titulo: "Día 10", texto: "Hoy es el día 10 del lindo mes santo este dia hay que recordar y alabar por que somos novios, por una propuesta mia y por que tu te arriesgaste a aceptarme, gracias por eso, gracias por permitirme estar a tu lado te amo mi hermosa ISI." },
      { titulo: "Día 11", texto: "Hoy es el día 11 del bello mes santo este dia quiero decir que yo considero el nombre Isis es decir tu nombre como una forma mas de alago, para mi presiosa es sinonimo de Isis, asi que cada que te digo Isis para mi es llamarte presiosa te amo mucho mi hermosa Diosa Isis." },
      { titulo: "Día 12", texto: "Hoy es el día 12 del Isis mes santo, ya dije que mes gusta tu nombre no? jasjjasj, pues me encanta y si quiero hacer 2 dias para decir que me encanta lo hare y que tieneeeeeeee, me facina es unico y especial te amo te amo en serio mi hermosa Isis." },
      { titulo: "Día 13", texto: "Hoy es el día 13 del grandioso mes santo, este dia te dire de una vez por que te llamo mi Diosa, nop mejor preguntame y te lo respondo esta vez sipi, te amo tanto mi hermosa Isis, eres el amor de mi vida, gracias por seguir conmigo, te amo demaciadooooooooooooooooooo." },
      { titulo: "Día 14", texto: "Hoy es el día 14 del magico mes santo, hoy ya paso 7 dias desde tu cumpleañitos, pero para mi sigue siento un mes santo y mes increible asi que hay que seguir festejando, hoy pideme lo que sea que lo cumplooo por que este dia quiero ser mas un subdito tuyo amor mio, te amo demaciado TE AMO." },
      { titulo: "Día 15", texto: "Hoy es el día 15 del alabador mes santo, hoy quiero alabar esos hermosos lunares tan lindos y tan unicos me encatan todos los que tenes, te amo mi linda Diosa te AMO mucho mucho." },
      { titulo: "Día 16", texto: "Hoy es el día 16 del jubiloso mes santo hoy quiero proponerte una tradicion para este hermoso mes, que te parece si este mes comemos unas hamburgesas? que dices eh? yo invito obiamente, este noche cuando salgas una rica hamburgesa, aunque mas rica que tu lo dudo jasjajsjasj, te amo mi hermosa Diosa Isis." },
      { titulo: "Día 17", texto: "Hoy es el día 17 del alagador mes santo este dia quiero alagarte incluso mucho mas que antes, quiero expresarme aun mas contigo y que estemos aun mas juntos, te amo demaciado eres el amor de mi vida, te quiero con todo mi ser te amo de verdad TE AMOOOOOOOO." },
      { titulo: "Día 18", texto: "Hoy es el día 18 del maravilloso mes santo este hoy quiero ver peliculas contigo, se puede? quiero ver muchas, quiero que este dia pasarlo hablando de las peliculas que vimosssss te amo demaciado TE AMOOOOOOO" },
      { titulo: "Día 19", texto: "Hoy es el día 19 del bonito mes santo, en este dia te dire el primer pensamiento que tuve cuando te conoci, oooooo mejor nop lo guardare para el final jasjajsjjsaja te amo mucho mi hermosa y tierna Isis." },
      { titulo: "Día 20", texto: "Hoy es el día 20 del glorioso mes santo, quiero decirte que empiezes tu semana nueva llena de felicidad solo quiero que este dia estes con una sonrisa, y por eso, te recordare cada rato lo linda que eres, asi pararas sonriendo, te amo mi hermosa y linda noviecita jajsjas te amo de verdad." },
      { titulo: "Día 21", texto: "Hoy es el día 21 del orgulloso mes santo, ayer te dije lo bonita que eres a cada rato, asi que hoy quiero que tu digas lo bonita que eres y que actues orgullosamente cada rato, si te pregunto algo o te digo algo tiene que decir es por que soy muy bonita, y asi a cualquier persona, te amo mi linda Isis te amo de verdad mi linda noviecita." },
      { titulo: "Día 22", texto: "Hoy es el día 22 del dulce mes santo, este dia este dia tambien festejamos, que por que? por que sigue siendo el mes santo obvio, este dia hay que comer cosas dulces por que? nose quiero crear tradiciones contigo mi linda Isis, hagamos algo, hoy gana quien coma mas cosas dulces quieres? aceptas? el perdedor hara lo que la otra persona digaa, ajsjajsja bueno bueno te amoooooo mi hermosa Isis." },
      { titulo: "Día 23", texto: "Hoy es el día 23 del resplandeciente mes samto, este dia quiero que lo recordes nuevamente lo mucho que te amo te amo bastante demaciadno diria yo, te amo mucho mi linda Isis, eres muy especial para mi TE AMOOOOO." },
      { titulo: "Día 24", texto: "Hoy es el día 24 del soniriente mes santo, este dia quiero que hagas algo importante quiero que este alegre sonrie salta baila, por la linda relacion que tenemos quiero que este dia estes aun mas feliz que antes, te amo TE AMOOOOOO." },
      { titulo: "Día 25", texto: "Hoy es el día 25 del angelical mes santo, este dia, me gustaria decirte angel todo el dia pero recorde que una Diosa es mas que un angel asi que Diosa me gusta masssss, te amo mucho mi lindo angelito (no me quedaria con las ganasssssssss) te amoooo." },
      { titulo: "Día 26", texto: "Hoy es el día 26 del elegante mes santo como es domingo este dia tendria que ser para postrarse al altar asi que hay que ponernos nuestra mejor ropa (aunque tu siempre la traes lindaaaaaa) te amo mucho mi linda Diosa." },
      { titulo: "Día 27", texto: "Hoy es el día 27 del Calenturiento mes santo, y no este dia se llama asi por que me gustaria estar pegado a ti todo el dia, estar abrazado de ti y hacer de todo jasjajsjja te amo tanto mi linda Isis eres hermosa." },
      { titulo: "Día 28", texto: "Hoy es el día 28 del brillante mes santo, este dia quiero que brilles sobre todos los demas este dia quiero que solo te mires a ti en el espejo y digas estoy radiante y hermosa, asi quiero que sea este dia, te amo mi linda Isis." },
      { titulo: "Día 29", texto: "Hoy es el día 29 del perfecto mes santo, llego la hora de decirte que pense o cual fue mi primer pensamiento de ti, y fueeeeeeeeee, PERFECTA fue eso la palabra la unica que pense que perfecta, tus gustos tu forma de ver las cosas tu interes tu amor por las cosas que tambien te gustan, fue perfecto simplemente perfeccion ante todo, te amo mi perfecta DIOSA ISISSSSSSSSSSSSSSSSSSSSSSSSSS." },
      { titulo: "Día 30", texto: "Hoy es el día 30 del sensasional mes santo, hoy quiero decirnos aun mas veces te amo, quiero que sea un dia lleno de TE AMOSSSSSSS, yo comienzo, TE AMO te amo te amo te amo te amo te amo te amo te amo te amo te amo te amo te amo TE AMOOOOOOO mi preciosa Isis." },
      { titulo: "Día 31", texto: "Hoy es el día 31 del tu ponle nombreeeeee, este dia quiero que lo nombres tu, es el ultimo dia del mes santo :c , pero no importa cada mes es igual de lindo si estoy contigo, ponle nombre y dime todo lo que te gusto y lo que no, te escucho mi linda y perfecta Diosa ISIS, GRACIAS POR SEGUIR CONMIGO GRACIAS POR PERMITIRME ESTAR EN TU CUMPLEAÑOS Y PARTICIPAR DE LOS MOMENTOS IMPORTANTES DE TU VIDA, TE AMO TE AMO SERIAMENTE, ERES TAN HERMOSA Y LINDA TE AMO." }
    ];
    console.log("[DayModel] creado con", this.days.length, "días");
  }

  getTotal() {
    return this.days.length;
  }

  getByIndex(idx) {
    return this.days[idx] ?? null;
  }
}
